name:                Day2
version:             0.1.0.0
github:              "PilchardFriendly/Day2"
license:             BSD3
author:              "Nick Drew"
maintainer:          "nick.s.drew@gmail.com"
copyright:           "(C) 2019 Nick Drew"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PilchardFriendly/Day2#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- multiset
- text
- interpolatedstring-perl6
- attoparsec

library:
  source-dirs: src

executables:
  Day2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day2

tests:
  Day2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day2
    - hspec >= 2.2
